on:
  push:
    branches:
      - master
jobs:
  kubeval-chart:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s:
          - v1.20.5
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run kubeval
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: .github/kubeval.sh
