name: Build docker image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker-registry.patst.de/patst/cert-manager-webhook-godaddy:$GITHUB_SHA
    #- uses: actions/docker/login@master
    #  env:
    #    DOCKER_REGISTRY_URL: docker.pkg.github.com
    #    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    #    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push the Docker image
      env:
        DOCKER_REGISTRY_URL: docker-registry.patst.de
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY_URL
        docker push docker-registry.patst.de/patst/cert-manager-webhook-godaddy:$GITHUB_SHA
    - name: Push helm chart
      uses: patst/helm-push-action@master
      env:
        SOURCE_DIR: '.'
        CHART_FOLDER: 'deploy/godaddy-webhook'
        FORCE: 'True'
        CHARTMUSEUM_URL: 'https://chartmuseum.patst.de'
        #CHARTMUSEUM_USER: '${{ secrets.CHARTMUSEUM_USER }}'
        #CHARTMUSEUM_PASSWORD: ${{ secrets.CHARTMUSEUM_PASSWORD }}
